name: Format PHP
on:
  pull_request:
jobs
  model_docblocks:
    runs-on: ubuntu-latest
    if: github.event.pull_request.draft == false
    steps:
      - uses: actions/checkout@v2
      - uses: shivammathur/setup-php@v2
        with:
          php-version: 8.0
      - uses: ramsey/composer-install@v1
      - run: php artisan ide-helper:models --smart-reset
      - id: diff
        run: |
          git diff-index --name-only HEAD
          echo ::set-output name=modified::$(git diff-index --quiet HEAD && echo "false" || echo "true")
      - if: steps.diff.outputs.modified == 'true'
        run: |
          # git config --global user.name 'Actions'
          # git config --global user.email 'actions@github.com'
          git commit -am "[bot] Update model doc blocks"
          git push
